# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "chore"
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    allow:
      - dependency-type: "direct"
    groups:
      npm-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react"
        versions: ["19.x"]
      - dependency-name: "react-dom"
        versions: ["19.x"]
      - dependency-name: "@types/react"
        versions: ["19.x"]
      - dependency-name: "@types/react-dom"
        versions: ["19.x"]
      # Some dependencies are not compatible with the latest versions yet.
      - dependency-name: "typescript"
        versions: [">6"]
      # Keep the version to align with the current stable WordPress version.
      - dependency-name: "@wordpress/icons"
        versions: [">11"]
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "chore"
      - "npm"

  - package-ecosystem: "composer"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      composer-require:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      composer-require-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "phpunit/phpunit"
    labels:
      - "dependencies"
      - "chore"
      - "composer"
