name: publish

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Setup Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-7.4-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-7.4-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build

      - name: Publish (NPM)
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx lerna publish from-package --yes --pre-dist-tag next
